# Generated by Django 2.2.6 on 2019-11-04 09:11
import commutes.utils
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usage_type",
                    models.IntegerField(
                        choices=[(1, "TO_WORK"), (2, "MEETING"), (3, "OTHER")],
                        default=commutes.utils.CommuteUsageTypes(1),
                        verbose_name="利用種別",
                    ),
                ),
                (
                    "departure_station",
                    models.CharField(max_length=255, verbose_name="出発駅"),
                ),
                (
                    "arrival_station",
                    models.CharField(max_length=255, verbose_name="到着駅"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金額"
                    ),
                ),
                ("date_of_use", models.DateField(verbose_name="利用日")),
                ("has_apply", models.BooleanField(default=False, verbose_name="申請済み")),
            ],
        )
    ]
