# Generated by Django 2.2.6 on 2019-11-04 13:19
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("commutes", "0002_commute_user")]

    operations = [
        migrations.AddField(
            model_name="commute",
            name="usage_text",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="種別「その他」の場合に入力"
            ),
        )
    ]
